### PR TITLE
fix Error exposing secret in the logs

### LINKED ISSUE #2401: Clear text secrets in ESO logs
**Describe the bug**

When there's a mistake referencing a secret with the the ExternalSecret object, it logs into the logs the credentials it is using:

```
external-secrets-main-7f56bc8b9f-qd55g external-secrets {"level":"error","ts":1686216778.8303626,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"_REDACTED_","namespace":"_REDACTED_"},"namespace":"_REDACTED_","name":"_REDACTED_","reconcileID":"b052d569-8c42-4238-9e1d-2d9ca5848737","error":"IncompleteSignature: '\"_REDACTED_\"' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential={\"UserName\": \"_REDACTED_\", \"AccessKeyId\": \"_REDACTED_\", \"Status\": \"_REDACTED_\", \"SecretAccessKey\": \"_REDACTED_\", \"CreateDate\": \"_REDACTED_\", \"DeleteOn\": \"_REDACTED_\"}/20230608/us-east-1/sts/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=f623777514cafa003df7f48353c822dacfde3a498dc5ae964efba5e393ae2496'.\n\tstatus code: 400, ","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
```

**To Reproduce**

1. relevant manifests

SecretStore

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: demo-ss
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: AccessKeyId
            name: demo-aws
          secretAccessKeySecretRef:
            key: SecretAccessKey
            name: demo-aws
      region: eu-central-1
      role: arn:aws:iam::_REDACTED_:role/_REDACTED_
      service: SecretsManager
  retrySettings:
    maxRetries: 5
    retryInterval: 10s
```

ExternalSecret

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-aws
spec:
  data:
  - remoteRef:
      key: /AWSCreds
      property: AccessKeyId
      version: AWSCURRENT
    secretKey: AccessKeyId
  - remoteRef:
      key: /AWSCreds
      property: SecretAccessKey
      version: AWSCURRENT
    secretKey: SecretAccessKey
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: demo-ss
  target:
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      metadata:
        labels: {}
      type: Opaque
```

Apply first this manifest, so that everything works, then update the ExternalSecret removing the targeting a the property like this:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-aws
spec:
  data:
  - remoteRef:
      key: /AWSCreds
    secretKey: AccessKeyId
  - remoteRef:
      key: /AWSCreds
    secretKey: SecretAccessKey
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: demo-ss
  target:
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      metadata:
        labels: {}
      type: Opaque
```

3. Kubernetes and ESO version

Kubernetes: v1.25.8+37a9a08
ESO: 0.8.3

**Expected behavior**
Redacted or excluded secrets for **error** level, maybe changing the level to debug would be just fine

### PR DESCRIPTION
**Pull request by jordiprats**
## Problem Statement
When there's a mistake referencing a secret with the the ExternalSecret object, it logs into the logs the credentials it is using:

```
external-secrets-main-7f56bc8b9f-qd55g external-secrets {"level":"error","ts":1686216778.8303626,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"_REDACTED_","namespace":"_REDACTED_"},"namespace":"_REDACTED_","name":"_REDACTED_","reconcileID":"b052d569-8c42-4238-9e1d-2d9ca5848737","error":"IncompleteSignature: '\"_REDACTED_\"' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential={\"UserName\": \"_REDACTED_\", \"AccessKeyId\": \"_REDACTED_\", \"Status\": \"_REDACTED_\", \"SecretAccessKey\": \"_REDACTED_\", \"CreateDate\": \"_REDACTED_\", \"DeleteOn\": \"_REDACTED_\"}/20230608/us-east-1/sts/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=f623777514cafa003df7f48353c822dacfde3a498dc5ae964efba5e393ae2496'.\n\tstatus code: 400, ","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
```

## Related Issue

Fixes #2401

## Proposed Changes

Since it is the AWS client that returns the error message with the secret (the 

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

File: pkg/provider/aws/secretsmanager/secretsmanager.go [hunk 1]
```diff
@@ -460,7 +460,7 @@ func (sm *SecretsManager) Validate() (esv1beta1.ValidationResult, error) {
 	}
 	_, err := sm.sess.Config.Credentials.Get()
 	if err != nil {
-		return esv1beta1.ValidationResultError, err
+		return esv1beta1.ValidationResultError, fmt.Errorf("Error retrieving AWS credentials")
```
Comment (moolen) [inline pkg/provider/aws/secretsmanager/secretsmanager.go:463]: The `err` contains valuable information such as `IncompleteSignature`, i think it would be great if we can keep that information and scrub only the credentials.

We have this func:
https://github.com/external-secrets/external-secrets/blob/51e309258f1637159368459885a0c9783f90783c/pkg/provider/aws/util/errors.go#L27C12-L29

that removes the request-id from the error. Maybe we can extend it to scrub the credentials from the error.

Comment (jordiprats) [reply pkg/provider/aws/secretsmanager/secretsmanager.go]: Hi @moolen, I've updated the PR with the proposed change. The regex is removing everything after the credentials because they can be pretty much anything and we are not going to lose much anyway.

Comment (moolen) [reply pkg/provider/aws/secretsmanager/secretsmanager.go]: This sounds reasonable, thank you :heart:

**Comment by jordiprats** [comment]
I've updated the PR fixing the checks that failed

**Review by moolen — APPROVED** [review]
LGTM! Thank you for this, much appreciated :bow:
