### PR TITLE
infisical: support secrets within paths for `data` references

### LINKED ISSUE #4298: [Infisical] accessing nested items doesn't let you choose folder
**Describe the bug**
When trying to access nested items (SecretStore has `recursive: true` set), it's not possible to choose the path where a secret should lie.
With `data`, I can only fetch secrets of root layer.
With `dataFrom`, I can fetch secrets from the whole recursive filestructure specified in the SecretStore, but I cannot provide a path, so when a key is used multiple times, it's random which secret is fetched.

**To Reproduce**
Infisical Version: 1.3.0
External-Secrets Version: 0.12.1
Kubernetes Version: v1.29.11
1. Create a Test Secrets Project in Infisical called test-for-github with the following Secrets Layout:
  ```
  SECRET_LAYER_0 -> Value: SECRET_LAYER_0
  folder0
    UNIQUE_SECRET -> Value: UNIQUE_SECRET
    SECRET_LAYER_1 -> Value: SECRET_LAYER_1_0
  folder1
    SECRET_LAYER_1 -> Value: SECRET_LAYER_1_1
  ```
2. Create a Machine identity with role Admin (just for testing, reduce it if you want) to the Project.
3. Add a Secret with the Client Credentials to the Kubernetes Test Namespace (for naming, see SecretStore Manifest)
4. Create a SecretStore like this:
  ```
  apiVersion: external-secrets.io/v1beta1
  kind: SecretStore
  metadata:
    name: test-for-github
  spec:
    provider:
      infisical:
        auth:
          universalAuthCredentials:
            clientId:
              key: clientId
              name: infisical-creds
            clientSecret:
              key: clientSecret
              name: infisical-creds
        hostAPI: https://infisical.example.com # ChangeThis
        secretsScope:
          environmentSlug: staging
          projectSlug: test-for-github-dbn-j # ChangeThis
          recursive: true
          secretsPath: /
  ```
5. Create an External Secret (different Options and their results as comments in Manifest):
  ```
  apiVersion: external-secrets.io/v1beta1
  kind: ExternalSecret
  metadata:
    name: es-test
  spec:
    refreshInterval: 1m
    secretStoreRef:
      name: test-for-github
      kind: SecretStore
    target:
      name: es-test
      creationPolicy: Owner
    data:
    # ### Option 1: simple access
    # # Result: Works for Secrets in 0. Layer (SECRET_LAYER_0), but when specifying something else, the key is ""
    # - secretKey: key
    #   remoteRef:
    #     key: SECRET_LAYER_0 # SECRET_LAYER_0 or SECRET_LAYER_1 or UNIQUE_SECRET
    # ### Option 2: data with path
    # # Result: doesn't work, because it's using the whole path as "Secret-Key" with `secretPath=/`, therefore its key is ""
    # # See Logline: "Route GET:/api/v3/secrets/raw/folder0/SECRET_LAYER_1?environment=staging&include_imports=true&secretPath=%2F&workspaceSlug=test-for-github-dbn-j not found"
    # - secretKey: key
    #   remoteRef:
    #     key: folder0/SECRET_LAYER_1
    # ### Option 3: dataFrom with name
    # # Result: Works with `SECRET_LAYER_0` and `UNIQUE_SECRET`, but with `SECRET_LAYER_1`, it saves value `SECRET_LAYER_1_1`
    # dataFrom:
    # - find:
    #     name:
    #       regexp: "SECRET_LAYER_1"
    # ### Option4: dataFrom with path and name
    # # Result: doesn't work at all. As soon as I specify `path`, it doesn't create a secret anymore
    # # The Log-Lines also don't show anything, only the requests of the SecretStore to `"/api/v3/secrets/raw?environment=staging&expandSecretReferences=true&include_imports=true&recursive=true&secretPath=%2F&workspaceSlug=test-for-github-dbn-j"`
    # dataFrom:
    # - find:
    #     path: folder0
    #     name: 
    #       regexp: "SECRET_LAYER_1"
  ```

**Expected behavior**
When creating a SecretStore with `spec.provider.infisical.secretsScope.recursive=true` and creating an External-Secret with
  ```
  dataFrom:
    - find:
        path: folder0
        name: 
          regexp: "SECRET_LAYER_1"
  ```
it should access the Secret `folder0/SECRET_LAYER_1`. Instead it doesn't create the Secret and sets the External-Secret to the state `SecretSynced` with message "secret retained due to DeletionPolicy=Retain"

**Additional context**
I've checked the Request that is done by the SecretStore
```
curl --request GET \
  --url 'https://infisical.example.com/api/v3/secrets/raw?environment=staging&expandSecretReferences=true&include_imports=true&recursive=true&secretPath=%252F&workspaceSlug=test-for-github-dbn-j' \
  --header 'authorization: Bearer SECRETBEARERTOKEN'
```
and it returns all the secrets, even both SECRET_LAYER_1 with their different values, but also different `secretPath`'s.

### PR DESCRIPTION
**Pull request by lgo**
(cc @akhilmhdh)

## Problem Statement

When attempting to access a secret in a directory, provided `secretsPath: /`, like so:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infisical-managed-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical
  target:
    name: auth-api
  data:
    - secretKey: API_KEY
      remoteRef:
        key: "foo/bar"
``` 

This will always result in a 404 API error from Infisical, because the API request is malformed (`/api/v3/secrets/raw/foo/bar`). The correct API request would instead be `/api/v3/secrets/raw/bar?secretPath=/foo`. This either:
- Made it so you simply cannot use secrets in folders with direct references via `data`
- Made it so you have to use a separate secret provider with a distinct `path`, which isn't very usable or very obvious

In combination with #4059, this would result in empty secrets but after that issue is fixed these would fail to sync with an error.

Overall this was also quite confusing with the `SecretStore`'s `secretsPath` property - would a `remoteRef` be an additive path? Would it supercede the `SecretStore`?

## Related Issue

Fixes #4298

## Proposed Changes

As suggested on the issue (https://github.com/external-secrets/external-secrets/issues/4298#issuecomment-2600966462) this makes a particular changes:
- `remoteRef`'s with paths take precedence over any `secretsPath` on the `SecretStore`
- If a `remoteRef` is detected to be a path (i.e. it contains `/`), an error is raised if it does not start with `/` with an actionable error indicating to use `/` and that it is an absolute reference. This should hopefuly further clarify the interaction between this, and `secretsPath`
- Documentation is updated with more specific examples of data in Infisical and how you would retrieve it, now that these features work

I've tested this against a self-hosted Infisical instance. I used a branch rebased off of #4304 to test this ([lgo:joey-infisical-folder-handling-testing](https://github.com/lgo/external-secrets/tree/joey-infisical-folder-handling-testing))
- With a `remoteRef: {key: "foo/bar"}`
- :x: `ExternalSecret` expectedly fails with `a secret key referencing a folder must start with a '/' as it is an absolute path, key: foo/bar`
- With a `remoteKey: {key: "/foo/bar"}`
- ✅ the secret successfully syncs.

**TODO**:
- [x] This needs to be rebased after merging #4304. I had a few changes layered on that I'll include after the rebase.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [ ] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by akhilmhdh** [comment]
Hi @lgo 

That was quick. Code wise looking good to me. I'll do the application test today and give my approval on my side. 

One small issue is, can we bring back the secret path option. Removing it would be a breaking change and want to keep it backward compatibility as much as we can. Simply keep that option as it is and if user provides and not `defaultSecretPath`, it will be used. The docs can be kept with new one, may be mentioning `secretPath is depreciated` would be great. As both option was optional from the start, this should give customers less headache.

**Comment by lgo** [comment]
> One small issue is, can we bring back the secret path option. Removing it would be a breaking change and want to keep it backward compatible. Simply keep that option as it is and if user provides it and not defaultSecretPath, the first one will be used. The docs can be kept with new one, may be mentioning secretPath is depreciated would be great. As both option was optional from the start, this should give customers less headache.

Sounds good. We could also just keep `secretPath` and ensure the documentation is clear. Your suggestion of keeping it around if we do add `defaultSecretPath` is a much better idea than changing it.

**Comment by lgo** [comment]
I decided to just avoid adding/changing `defaultSecretPath` and pushed up the changes, a few test fixes, and quality check fixes. This should now be good and just has a few test conflicts with the other PR (which I'll address once it's in).

**Comment by Skarlso** [comment]
@lgo Hello 👋  Could you please sign your commits? :)

**Comment by lgo** [comment]
Done! Sorry, I was away on a trip. I have not yet had a chance to build out the e2e tests either.

Hi @akhilmhdh - just checking if you had any additional testing you'd like to do on your end before checking off?

**Comment by Skarlso** [comment]
Is this now ready for review?

File: pkg/provider/infisical/client.go [hunk 1]
```diff
@@ -43,14 +43,44 @@ func getPropertyValue(jsonData, propertyName, keyName string) ([]byte, error) {
...
+	if !strings.HasPrefix(key, "/") {
+		return "", "", fmt.Errorf("a secret key referencing a folder must start with a '/' as it is an absolute path, key: %s", key)
+	}
+
+	// Otherwise, take the prefix from `key` and use that as the path. We intentionally discard
+	// `defaultPath`.
+	keyParts := strings.Split(key, "/")
+	keySuffix := keyParts[len(keyParts)-1]
+	path := strings.Join(keyParts[:len(keyParts)-1], "/")
+	return path, keySuffix, nil
```
Comment (Skarlso) [inline pkg/provider/infisical/client.go:68]:
```suggestion
	lastIndex := strings.LastIndex(key, "/")
	return key[lastIndex+1:], key[:lastIndex], nil
```

File: pkg/provider/infisical/provider.go [hunk 2]
```diff
@@ -95,13 +95,18 @@ func (p *Provider) NewClient(ctx context.Context, store esv1beta1.GenericStore,
 			return nil, fmt.Errorf("failed to authenticate via universal auth %w", err)
 		}
 
+		secretPath := infisicalSpec.SecretsScope.SecretsPath
+		if secretPath == "" {
+			secretPath = "/"
```
Comment (Skarlso) [inline pkg/provider/infisical/provider.go:100]: Won't this break existing things? Like, if you expected this path not to be set previously, it will be defaulted now to `/`.

**Comment by gusfcarvalho** [comment]
Hi @lgo ! Were you able to address the points @Skarlso mentioned?

**Comment by akhilmhdh** [comment]
Hi @Skarlso @gusfcarvalho @lgo 

I don't have push access to this branch. Can I make the changes as another PR with your commits to make this merged, if @lgo doesn't have time to continue working on it? We would love to see this changes getting shipped.

**Comment by gusfcarvalho** [comment]
As long as you’re fork from @lgo repo, so his contributions are correctly accredited to him, I’m up for it 😄

**Comment by lgo** [comment]
Heh, yea - sorry this went stale! I haven't had a lot of spare time lately and I've worked around this by using a custom build that included this patch.

Do feel free to fork this to take it over the finish line (if you don't get to it by EOW, I do have a long weekend that I can likely complete this!)

**Comment by lgo** [comment]
(actually, I'll go ahead and handle the rebase right now and the existing PR feedback just to leave a slightly cleaner slate, whether or not there's further work needed)

File: pkg/provider/infisical/provider.go (hunk 2 above)
Comment (lgo) [reply pkg/provider/infisical/provider.go:102]: I need to recall why exactly I added this, but I think it was necessary?

I believe ExternalSecrets didn't work at all if you pass a secret name that includes a `/`, so you can always assume the only secrets that worked were from the root (`/`) and I believe this cannot be simply `""` when making an API request but I'm doing a quick pass to figure out why.

Comment (lgo) [reply pkg/provider/infisical/provider.go:101]: Hmm I guess that's not necessarily true as `getSecretAddress` will return `("", "FOOBAR")` when the path is empty or has a `/`. I'll have to deploy this and test it.

**Comment by lgo** [comment]
Okay I've pushed up a rebase, squashed the commits down, and addressed the one feedback. Two things that still need to be done:
- [ ] Deploy this and step through the test cases I outlined again
- [ ] Check whether Infisical's API requires a leading `/` on the `secretPath` query param (https://infisical.com/docs/api-reference/endpoints/secrets/read#parameter-secret-path). If they do, I'll make this much clearer in the code as I've partially written up error / defensive cases for tihs.

**Comment by typedrat** [comment]
> Okay I've pushed up a rebase, squashed the commits down, and addressed the one feedback. Two things that still need to be done:
> 
>     * [ ]  Make sure the unit tests are still working. (For some reason `go test <file>` isn't working and `make unit-test` is failing but with a large wall of text so I need to revisit that)
> 
>     * [ ]  Deploy this and step through the test cases I outlined again
> 
>     * [ ]  Check whether Infisical's API requires a leading `/` on the `secretPath` query param (https://infisical.com/docs/api-reference/endpoints/secrets/read#parameter-secret-path). If they do, I'll make this much clearer in the code as I've partially written up error / defensive cases for tihs.
> 
> 
> I'll take a pass at this later tonight, or tomorrow morning, and see if I can wrap these items up.

Any updates on this? I really prefer using `external-secrets` over the native Infisical operator, and this would really help make it a lot more usable.

**Comment by gusfcarvalho** [comment]
Hi @typedrat! If you can take the remaining points from these commits and push your contribution to it, I’d gladly review it!

otherwise, chances are this might go stale just because that’s the nature of community driven effort 🤷🏽‍♂️

**Comment by typedrat** [comment]
> Hi @typedrat! If you can take the remaining points from these commits and push your contribution to it, I’d gladly review it!
> 
> otherwise, chances are this might go stale just because that’s the nature of community driven effort 🤷🏽‍♂️

Fair enough, I know how open source goes haha

I don't know Go and I've only got the barest bit of experience with using Infisical's API, so I don't know if I'm really the one to get this over the finish line myself, but I'll come back and look at this when I'm out of my work crunch if no one else has picked this up.

**Comment by Skarlso** [comment]
@typedrat I'll take a look. :)

File: pkg/provider/infisical/provider.go (hunk 2 above)
Comment (Skarlso) [reply pkg/provider/infisical/provider.go:101]: I verified the error. 👍

**Comment by Skarlso** [comment]
I had to rebase to get the signed commit to work, but I left an `On-behalf-of` in the commit message to make sure to credit OP. :)

**Comment by Adriien-M** [comment]
Thanks @Skarlso for your work 👍
