### PR TITLE
fix cert auth without token fixed #3926

### LINKED ISSUE #3926: kubernetes-provider auth broken after 0.9.20
**Describe the bug**
It seems that after the implementation of this feature for kubernetes provider on release v0.9.20: 

> add AuthRef to kubernetes provider fixes https://github.com/external-secrets/external-secrets/issues/3627 by @kaedwen in https://github.com/external-secrets/external-secrets/pull/3628

seems that stoped working only with "auth:" it gives the error:  could not get provider client: failed to prepare auth: no auth provider given

**To Reproduce**
Install version v.0.9.20 or newer

deploy a yaml like this:

``` yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-secretstore
spec:
  provider:
    kubernetes:
      remoteNamespace: shared-secrets
      server:
        url: "https://x.x.x.x:6443"
        caProvider:
          type: ConfigMap
          name: kube-root-ca
          key: ca.crt
          namespace: "external-secrets"
      auth:
        cert:
          clientCert:
            name: "cluster-client"
            key: "tls.crt"
          clientKey:
            name: "cluster-client"
            key: "tls.key"
```

**Expected behavior**
Keep working with auth

**Screenshots**
This is the status of kind: SecretStore
``` yaml
status:
  capabilities: ReadWrite
  conditions:
    - lastTransitionTime: '2024-09-18T13:11:54Z'
      message: unable to create client
      reason: InvalidProviderConfig
      status: 'False'
      type: Ready
```
      
And the two lines on logs that are generated constantly with the error on app.kubernetes.io/name=external-secrets pod
``` jsonl
{"level":"error","ts":1726665196.5949998,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":{"name":"k8s-alm-secretstore"},"error":"could not get provider client: failed to prepare auth: no auth provider given","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:69\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:65\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":1726665196.6100624,"msg":"Reconciler error","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","ClusterSecretStore":{"name":"k8s-alm-secretstore"},"namespace":"","name":"k8s-alm-secretstore","reconcileID":"a83fe0c9-b660-44e4-985f-b5d5c827ea95","error":"could not get provider client: failed to prepare auth: no auth provider given","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```

**Additional context**
Going back to 0.9.19 works perfect

### PR DESCRIPTION
**Pull request by kaedwen**
## Problem Statement

Issue stated that creating a SecretStore with key/cert only does fail

## Related Issue

Fixes #3926

## Proposed Changes

Do not fail when there is not token given

## Checklist

- [X] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [X] All commits are signed with `git commit --signoff`
- [X] My changes have reasonable test coverage
- [X] All tests pass with `make test`
- [X] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

File: pkg/provider/kubernetes/auth.go [hunk 1]
```diff
@@ -66,8 +66,6 @@ func (c *Client) getAuth(ctx context.Context) (*rest.Config, error) {
 		if err != nil {
 			return nil, fmt.Errorf("could not fetch Auth.ServiceAccount: %w", err)
 		}
-	} else {
```
Comment (Skarlso) [inline pkg/provider/kubernetes/auth.go:69]: This is not the correct fix. You need to put the below if statement into this.

Or rather, rewrite this whole else if section into a `switch` statement on Auth.Token, Auth.ServiceAccount and Auth.Cert. Then the default should be no auth provider given.

File: pkg/provider/kubernetes/auth_test.go [hunk 2]
```diff
@@ -250,28 +250,13 @@ func TestSetAuth(t *testing.T) {
 						"cert": []byte("my-cert"),
 						"key":  []byte("my-key"),
 					},
-				}, &corev1.Secret{
```
Comment (Skarlso) [inline pkg/provider/kubernetes/auth_test.go:253]: do not delete these

**Review by Skarlso — CHANGES_REQUESTED** [review]
As stated in the review comment above.

File: pkg/provider/kubernetes/auth.go (hunk 1 above)
Comment (kaedwen) [reply pkg/provider/kubernetes/auth.go:69]: ok had this in mind too, will refactor this

File: pkg/provider/kubernetes/auth_test.go (hunk 2 above)
Comment (kaedwen) [reply pkg/provider/kubernetes/auth_test.go:253]: this I have removed because than it reflects exactly why we have this bug in. Removing the token here is like not providing a token just a key/cert. Do you want me to create an additional step rather adjusting this one?

Comment (Skarlso) [reply pkg/provider/kubernetes/auth_test.go:253]: >this I have removed because than it reflects exactly why we have this bug in.

So yes, keep it in and expect it to fail.

Comment (kaedwen) [reply pkg/provider/kubernetes/auth_test.go:253]: We have to clarify the difference between the original implementation and how we want to have it in future.

The original one did take the token from a secret or from a given `ServiceAccount` and in addition it appended the key/cert when given.

The new approach would take just one, and the prio would be, 1. token from secret, 2. token from `ServiceAccount` and 3. the last one the key/cert pair.

I do wonder if somebody is interested in having a token and a key/cert in the config together. Feels weird but I do not know what the kube client does if it has multiple options to authenticate with.

The question is now if we should stick to the original implementation or not.

**Review by Skarlso — APPROVED** [review]

**Review by Skarlso — APPROVED** [review]
