### PR TITLE
fix: issue-5388: Fixes GCP Workload Identity Federation auth issue

### LINKED ISSUE #5388: GCP Workload Identity Federation - invalid token request when using a Service Account
**Describe the bug**
When using Workload Identity Federation in GCP, all attempts to setup a `SecretStore` with a `serviceAccountRef` all result with a status of `InvalidProviderConfig` with the following error message in the logs:

```
{"level":"error","ts":1759177167.2794123,"msg":"Reconciler error","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore","SecretStore":{"name":"testing-gcp","namespace":"testing"},"namespace":"testing","name":"testing-gcp","reconcileID":"e5dcb1ec-2a66-4ef1-a799-9af9ad478da3","error":"could not get provider client: unable to get credentials: invalid subject token request, audience is //iam.googleapis.com/projects/[REDACTED]/locations/global/workloadIdentityPools/core-external-pool/providers/core-cluster-provider(expected ) and subject_token_type is urn:ietf:params:oauth:token-type:jwt(expected urn:ietf:params:oauth:token-type:jwt)","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.1/pkg/internal/controller/controller.go:474\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.1/pkg/internal/controller/controller.go:421\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.1/pkg/internal/controller/controller.go:296"}
```

**To Reproduce**

Examples used:
```
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: testing-gcp
  namespace: testing
spec:
  provider:
    gcpsm:
      projectID: [REDACTED]
      auth:
        workloadIdentityFederation:
          audience: //iam.googleapis.com/projects/[REDACTED]/locations/global/workloadIdentityPools/core-external-pool/providers/core-cluster-provider
          serviceAccountRef:
            audiences:
            - //iam.googleapis.com/projects/[REDACTED]/locations/global/workloadIdentityPools/core-external-pool/providers/core-cluster-provider
            name: testing-gcp
            namespace: testing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testing-gcp
  namespace: testing

```
Kubernetes: v1.33.4
ESO: v0.20.1

**Expected behavior**
Expected SecretStore to be  `Valid`

**Screenshots**

**Additional context**
Looking at the codebase, it looks like the Token Supplier is created [before](https://github.com/external-secrets/external-secrets/blob/823261da4eea91612fa537d48d5901016a8b5b4b/pkg/provider/gcp/secretmanager/workload_identity_federation.go#L218) all of the defaults are applied. As it is impossible to also supply a `credsConfig` without failing validation, the audience is always blank.

Flipping these around locally gets it to work - happy to offer up a PR, but am entirely unfamiliar with the tests.

### PR DESCRIPTION
**Pull request by bharath-b-rh**
## Problem Statement

GCP Workload Identity Federation authentication fails when `serviceAccountRef` is specified.

## Related Issue

Fixes #5388 

## Proposed Changes

The issue is caused due to the incorrect initialization of the WIF audience.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

File: pkg/provider/gcp/secretmanager/workload_identity_federation.go [hunk 1]
```diff
@@ -295,7 +295,7 @@ func (w *workloadIdentityFederation) updateExternalAccountConfigWithSubjectToken
 		ns = *w.config.ServiceAccountRef.Namespace
 	}
 	config.SubjectTokenSupplier = &k8sSATokenReader{
-		audience:         config.Audience,
+		audience:         w.config.Audience,
```
Comment (Skarlso) [inline pkg/provider/gcp/secretmanager/workload_identity_federation.go:298]: Nice catch. I assume there were no tests for this? :D

**Review by Skarlso — APPROVED** [review]

File: pkg/provider/gcp/secretmanager/workload_identity_federation.go (hunk 1 above)
Comment (bharath-b-rh) [reply pkg/provider/gcp/secretmanager/workload_identity_federation.go:298]: Yeah, the manual e2e tests would have caught, not sure when this typo happened :)
