### PR TITLE
Fix skew between refreshInterval and refreshTime that can lead to skipped refresh.

### LINKED ISSUE #2812: refreshInterval is not respected with a combination of ExternalSecret and VaultDynamicSecret
**Describe the bug**
`ExternalSecret` refreshInterval is not respected when using a `VaultDynamicSecret` as generator. For example, for a `refreshInterval` of `20m`, we transiently get a "skipped" refresh. Which means our secret is only refreshed on the next `refreshInterval` so 40 minutes after the previous successful one.

No events are registered on the `ExternalSecret` when the skip happens, and no logs are emitted by the controller.
We do see an increase on the `externalsecret_sync_calls_total{name="test"}` metrics counter at every `refreshInterval` though.

**To Reproduce**
Create a `VaultDynamicSecret` to issue certs from Vault's PKI
Create an associated `ExternalSecret` with a `refreshInterval`. 

Example manifests:
```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: 20m
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: generator
spec:
  path: pki/main/issue/foo
  method: POST
  parameters:
    common_name: foo
    ttl: 30m
  provider: <redacted>
```

ESO Version: 0.9.7
Kube Version: v1.27.4-eks-2d98532

**Expected behavior**
A new certificate should be issued and stored into the `Secret` for each `refreshInterval` that elapse. 

**Screenshots**
N/A

**Additional context**
We generate certificates with short TTL and use `ExternalSecret` to refresh them before expiration.

### PR DESCRIPTION
**Pull request by vtorikianupgrade**
## Problem Statement

When the backend provider is slow to respond (eg: VaultDynamicSecret calling PKI issue endpoint), the `.status.refreshTime` is skewing which leads to every other refresh being skipped.

## Related Issue

Fixes #2812

## Proposed Changes

I went with the simplest solution, instead of setting refreshTime to `time.Now()` at the end of reconciliation, set it to `start`, which is initialized at the beginning of reconciliation.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Review by moolen — COMMENTED** [review]
Hey, great find! Thanks for digging and providing a fix.
I think this is a big contributing factor to the refresh problem. I think there's another issue here:

https://github.com/external-secrets/external-secrets/blob/0612404f6498f09f5355f92f54ac75c2610c528a/pkg/controllers/externalsecret/externalsecret_controller.go#L176-L183

Because here we return with a static requeue duration (say, `20m` like in your case). But actually we should return the time until the next refresh should happen (plus a bit of tolerance for clock skew etc).

Would you provide a fix for this as well? I wouldn't mind if you add to this PR, no need to open a separate PR for this.

**Comment by vtorikianupgrade** [comment]
Sorry @moolen I don't follow exactly.

What do you mean with the following:
> But actually we should return the time until the next refresh should happen (plus a bit of tolerance for clock skew etc).

Do we want to requeue with a "default" duration that is different that `.spec.RefreshInterval` ?

**Comment by vtorikianupgrade** [comment]
I get it, recompute a `RequeueAfter` value based on .status.RefreshTime instead of bumping the next refresh to the next `refreshInterval`.

**Comment by moolen** [comment]
Consider the following case:
ExternalSecret is supposed to refresh every 20m. The last time it reconciled was `10:00`, so the next time it should refresh would be `10:20`. However, if we restart the controller at the worst possible time at `10:19`, it requeues the externalSecret so that will reconcile at `10:39` - because we requeue with a static time `20m`


Instead of:
```go
// simplified
refreshInt := externalSecret.spec.RefreshInterval
if !shouldRefresh(externalSecret) { 
 	return ctrl.Result{RequeueAfter: refreshInt}, nil 
 } 
```

We should calculate the time when we should refresh and requeue, so that we reconcile at the correct time.

```go
refreshInt := externalSecret.spec.RefreshInterval
if !shouldRefresh(externalSecret) { 
        // time: 10:19
 	diff := refreshInterval - timeSinceLastRefresh + oneSecond // 20 - 19 = 1 (plus 1 second for tolerance)
 	diff := 20 - 19
 	return ctrl.Result{RequeueAfter: refreshInt}, nil 
 } 
```

**Comment by vtorikianupgrade** [comment]
```go
func shouldRefresh(es esv1beta1.ExternalSecret) bool {
	// refresh if resource version changed
	if es.Status.SyncedResourceVersion != getResourceVersion(es) {
		return true
	}

	// skip refresh if refresh interval is 0
	if es.Spec.RefreshInterval.Duration == 0 && es.Status.SyncedResourceVersion != "" {
		return false
	}
	if es.Status.RefreshTime.IsZero() {
		return true
	}
        return es.Status.RefreshTime.Add(es.Spec.RefreshInterval.Duration).Before(time.Now().Add(-20 * time.Second))
}
```
This should cover any potential skew. Do we want that skew to be configurable or keep it hardcoded as in this example ?

**Comment by moolen** [comment]
I would keep the skew hardcoded for now, if there's a need we can still make it configurable if needed.
Not sure about the value though, my gut feeling says a couple (1-5) of seconds. There are some users that rely on short refresh intervals (~30s)

File: pkg/controllers/externalsecret/externalsecret_controller.go [hunk 1]
```diff
@@ -575,7 +575,7 @@ func shouldRefresh(es esv1beta1.ExternalSecret) bool {
 	if es.Status.RefreshTime.IsZero() {
 		return true
 	}
-	return es.Status.RefreshTime.Add(es.Spec.RefreshInterval.Duration).Before(time.Now())
+	return es.Status.RefreshTime.Add(es.Spec.RefreshInterval.Duration).Before(time.Now().Add(-20 * time.Second))
```
Comment (moolen) [inline pkg/controllers/externalsecret/externalsecret_controller.go:578]: The `bool` returned here is not the problem, the `RequeueAfter` needs to be changed so it'll reconcile at the right time :pray:

**Comment by vtorikianupgrade** [comment]
> I would keep the skew hardcoded for now, if there's a need we can still make it configurable if needed. Not sure about the value though, my gut feeling says a couple (1-5) of seconds. There are some users that rely on short refresh intervals (~30s)

Even in the case of short refresh

File: pkg/controllers/externalsecret/externalsecret_controller.go (hunk 1 above)
Comment (vtorikianupgrade) [reply pkg/controllers/externalsecret/externalsecret_controller.go]: Gotcha.

**Comment by vtorikianupgrade** [comment]
I put a 5 seconds skew, as suggested.

**Review by moolen — APPROVED** [review]
LGTM, thank you for the fix :medal_sports: !
