### PR TITLE
fix: set client transport to use GitHub Enterprise URL

### LINKED ISSUE #5661: GitHub Enterprise authentication issue
**Describe the bug**

When using the GitHub provider with a custom URL set to a GitHub Enterprise server, authentication is done using https://api.github.com instead of https://github.<enterprise>.com

In the ESO logs, the following error appear:

```
{
  "level": "error",
  "ts": 1764002946.1677747,
  "logger": "controllers.SecretStore",
  "msg": "unable to validate store",
  "secretstore": {
    "name": "github-backend-store",
    "namespace": "my-namespace"
  },
  "error": "could not validate provider: store is not allowed to list secrets: Get \"https://github.enterprise.com/api/v3/repos/MyOrganization/MyRepository/actions/secrets\": could not refresh installation id 23's token: received non 2xx response status \"404 Not Found\" when fetching https://api.github.com/app/installations/23/access_tokens",
  "stacktrace": "github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:107\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*StoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/secretstore_controller.go:72\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.1/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.1/pkg/internal/controller/controller.go:461\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.1/pkg/internal/controller/controller.go:421\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.1/pkg/internal/controller/controller.go:296"
}
```

**To Reproduce**
1. provide all relevant manifests

```
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: github-backend-store
  namespace: my-namespace
spec:
  provider:
    github:
      url: https://github.enterprise.com/
      appID: 1
      installationID: 23
      auth:
        privateKey:
          name: github-privatekey-secret
          key: privateKey.pem
      organization: MyOrganization
      repository: MyRepository
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gha-pushsecret
  namespace: my-namespace
spec:
  refreshInterval: 15m
  secretStoreRefs:
    - name: github-backend-store
      kind: SecretStore
  selector:
    secret:
      name: my-secret
  data:
    - match:
        secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          remoteKey: ACCESS_KEY_ID
    - match:
        secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          remoteKey: SECRET_ACCESS_KEY
---
```

2. provide the Kubernetes and ESO version:

0.20.2 but from the tests I did, the issue exists on the tip

**Expected behavior**
Authentication should be done against the GitHub Enterprise server, not api.github.com

PR #5662 has been submitted to fix the issue

### PR DESCRIPTION
**Pull request by fred-gagnon**
## Problem Statement

When using the GitHub provider with a custom URL set to a GitHub Enterprise server, authentication is done using https://api.github.com instead of https://github.enterprise.com

## Related Issue

Fixes #5661 

## Proposed Changes

When using a custom GitHub Enterprise URL, the HTTP client transport must be overridden to also use the custom GitHub Enterprise URL

## Format

Please ensure that your PR follows the following format for the title:
```
feat(scope): add new feature
fix(scope): fix bug
docs(scope): update documentation
chore(scope): update build tool or dependencies
ref(scope): refactor code
clean(scope): provider cleanup
test(scope): add tests
perf(scope): improve performance
desig(scope): improve design
```

Where `scope` is _optionally_ one of:
- charts
- release
- testing
- security
- templating

## Checklist

- [X] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [X] All commits are signed with `git commit --signoff`
- [X] My changes have reasonable test coverage
- [X] All tests pass with `make test`
- [X] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

File: providers/v1/github/auth.go [hunk 1]
```diff
@@ -47,7 +47,16 @@ func (g *Client) AuthWithPrivateKey(ctx context.Context) (*github.Client, error)
...
 		}
-		return client.WithEnterpriseURLs(g.provider.URL, uploadURL)
+
+		enterpriseClient, err := client.WithEnterpriseURLs(g.provider.URL, uploadURL)
+		if err != nil {
+			return nil, fmt.Errorf("could not instantiate new enterprise client: %w", err)
+		}
+
+		itr.BaseURL = enterpriseClient.BaseURL.String()
+		client.Client().Transport = itr
```
Comment (Skarlso) [inline providers/v1/github/auth.go]: This is weird. :D Why not create a new client with a proper transport instead?

Comment (fred-gagnon) [reply providers/v1/github/auth.go]: Done

Comment (fred-gagnon) [reply providers/v1/github/auth.go]: @Skarlso are you OK with the code change ?

Comment (Skarlso) [reply providers/v1/github/auth.go]: yep, looks good.

**Review by Skarlso — APPROVED** [review]
