### PR TITLE
fix: `webhook` support more types when parsing response

### LINKED ISSUE #2898: Unmarshalling issues with some JSON responses in webhook provider
**Describe the bug**
ESO webhook provider "crashes" on strings with escaped forward slahes.

**To Reproduce**
I'm using ESO v0.9.4 with the webhook provider. I use it to extract an authentication token from VENAFI TPP.
I use a `ClusterSecretStore` like this one:
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: venafi-webhook-backend
spec:
  provider:
    webhook:
      body: '{"username":"{{ .auth.username }}","password":"{{ .auth.password }}","client_id":
        "My_Client_ID","scope":"configuration:manage,delete;certificate:manage"}'
      headers:
        Accept: application/json
        Content-Type: application/json
      method: POST
      result:
        jsonPath: $.access_token
      secrets:
      - name: auth
        secretRef:
          name: venafi-webhook-credentials
          namespace: co
      timeout: 1m
      url: https://cert-manager.adidas.com/vedauth/authorize/oauth
```

I detected VENAFI was issuing more authentication tokens than expected, so digging into the logs I saw:
```
{"level":"error","ts":1700746900.245956,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":{"name":"venafi-webhook","namespace":"default"},"error":"failed to parse response json: yaml: found unknown escape character","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:205\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:226"}
```

The issue I identified is that access or refresh tokens can arrive with an escaped forward slash, i.e.:
```
{"access_token":"REDACTED","refresh_token":"RE\/DACTED==","expires_in":86399,"expires":1700833565,"token_type":"Bearer","scope":"certificate:manage;configuration:delete,manage","identity":"AD+mydomain.com:a748392498bcb42323427ac392ff","refresh_until":1700833565}%
```

In such cases, the Unmarshall method fails and I see the aforementioned error: `failed to parse response json: yaml: found unknown escape character`. Because of this error, ESO assumes the request has failed and it enqueues it, leading to that increase of tokens issued. The valid token is the one without the backslash.

I've tried to do a simple `strings.ReplaceAll(string(result), '\/', '/')`  on the code after `getWebhookData` and works correctly, but I'm not sure if that's the best approach (considering that probably it's just VENAFI the only one that fails this way).

What could be the best approach to sanitize the strings? unquote and replaceall? remove all single blackslash? a regexp to which replaces `\/` by `/` if `[^\\]\\/` ?

(Ideally fixing VENAFI, but that also seems difficult)

WDYT?

**Expected behavior**
I expect to fetch correctly the access_token from that JSON.

### PR DESCRIPTION
**Pull request by moolen**
## Problem Statement
This PR fixes a couple of bugs in the webhook provider:
1. webhook provider tries to coerce the type to (string) and panics
2. #2898: properly handle escaped json
3. only a small set of response payload types were supported. This PR adds support for a wider variety
4. :broom: centralize the `getTypedKey` as it was copy-pasted across providers

## Related Issue

Fixes #2898

### CODE REVIEW

File: pkg/provider/webhook/webhook.go [hunk 1]
```diff
@@ -152,30 +153,54 @@ func (w *WebHook) GetSecret(ctx context.Context, ref esv1beta1.ExternalSecretDat
 	}
 	if resultJSONPath != "" {
 		jsondata := interface{}(nil)
-		if err := yaml.Unmarshal(result, &jsondata); err != nil {
+		if err := json.Unmarshal(result, &jsondata); err != nil {
```
Comment (moolen) [inline pkg/provider/webhook/webhook.go:156]: trying to decode as yaml caused #2898

File: pkg/provider/webhook/webhook.go [hunk 2]
```diff
@@ -152,30 +153,54 @@ func (w *WebHook) GetSecret(ctx context.Context, ref esv1beta1.ExternalSecretDat
...
+	case float64:
+		return []byte(strconv.FormatFloat(val, 'f', 0, 64)), nil
+	case []byte:
+		return val, nil
+	case string:
+		return []byte(val), nil
+
+	// due to backwards compatibility we must keep this!
+	// in case we see a []something we pick the first element and return it
+	case []interface{}:
```
Comment (Skarlso) [inline pkg/provider/webhook/webhook.go:188]:
```suggestion
	case []any:
```

just to be consistent. :D

File: pkg/utils/utils.go [hunk 3]
```diff
@@ -237,6 +238,44 @@ func MergeStringMap(dest, src map[string]string) {
 	}
 }
 
+const (
+	errUnexpectedKey = "unexpected key in data: %s"
+	errSecretType    = "can not handle secret value with type %T"
```
Comment (Skarlso) [inline pkg/utils/utils.go:243]: Since this is now an extracted method, I think the Errors should also be extracted if someone wants to check against them outside this package? WDYT?

File: pkg/provider/webhook/webhook.go [hunk 4]
```diff
@@ -152,30 +153,54 @@ func (w *WebHook) GetSecret(ctx context.Context, ref esv1beta1.ExternalSecretDat
...
-		return []byte(jsonvalue), nil
+		return extractSecretData(jsondata)
 	}
 
 	return result, nil
 }
 
+// tries to extract data from an interface{}
+// it is supposed to return a single value.
+func extractSecretData(jsondata interface{}) ([]byte, error) {
```
Comment (Skarlso) [inline pkg/provider/webhook/webhook.go:171]:
```suggestion
func extractSecretData(jsondata any) ([]byte, error) {
```

File: pkg/utils/utils.go [hunk 5]
```diff
@@ -237,6 +238,44 @@ func MergeStringMap(dest, src map[string]string) {
...
+)
+
+func GetByteValueFromMap(data map[string]interface{}, key string) ([]byte, error) {
+	v, ok := data[key]
+	if !ok {
+		return nil, fmt.Errorf(errUnexpectedKey, key)
+	}
+	return GetByteValue(v)
+}
+func GetByteValue(v interface{}) ([]byte, error) {
```
Comment (Skarlso) [inline pkg/utils/utils.go:253]: Nice refactoring! :)

**Review by Skarlso — APPROVED** [review]
