### PR TITLE
Address #3331 and #3080

### LINKED ISSUE #3080: Invalid certs when using cert-manager with CA issuer
**Describe the bug**
external-secrets version v0.9.11

When deploying ESO using cert-manager to replace cert controller, if cert-manager issuer is CA issuer, the external-secrets-webhook POD is unhealthy due to following error.

```
{"level":"info","ts":1706300660.7643616,"logger":"setup","msg":"validating certs"}
{"level":"error","ts":1706300660.7648668,"logger":"setup","msg":"invalid certs. retrying...","error":"x509: certificate signed by unknown authority","stacktrace":"github.com/external-secrets/external-secrets/cmd.waitForCerts\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:214\ngithub.com/external-secrets/external-secrets/cmd.glob..func3\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:83\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\ngithub.com/external-secrets/external-secrets/cmd.Execute\n\t/home/runner/work/external-secrets/external-secrets/cmd/root.go:254\nmain.main\n\t/home/runner/work/external-secrets/external-secrets/main.go:21\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/proc.go:267"}
```

**To Reproduce**
1. Create cert-manger issuer with CA issuer using intermediate CA. See: https://cert-manager.io/docs/configuration/ca/
2. Deploy ESO with following values.yaml
```
webhook:
  certManager:
    enabled: true
    addInjectorAnnotations: true
    cert:
      create: true
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: ca-issuer

certController:
  create: false
```

**Expected behavior**
external-secrets-webhook should be healthy.

**Screenshots**
N/A

**Additional context**
With SelfSigned issuer, the deployement works well. But my context is using CA issuer from cert-manager.

### LINKED ISSUE #3331: Webhook TLS Client Renegotiation Error
**Describe the bug**
When setting up a Webhook Provider connection to a Cyberark CCP Endpoint, it fails with error `local error: tls: no renegotiation`

Kubernetes provides this event message for the externalsecret object:
```
Events:
  Type     Reason        Age                From              Message
  ----     ------        ----               ----              -------
  Warning  UpdateFailed  2s (x12 over 13s)  external-secrets  error retrieving secret at .data[0], key: <cyberark username field>, err: failed to call endpoint: Get "https://ccp.example.com/AIMWebService/api/Accounts?ConnectionTimeout=30&AppId=MY-APPID&Query=Safe=MY-SAFE;UserName=<cyberark username field>;Address=<cyberark address field>": local error: tls: no renegotiation
```

**To Reproduce**
1. Create either a secretstore or clustersecretstore
```
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cyberark-test
spec:
  provider:
    webhook:
      url: "https://ccp.example.com/AIMWebService/api/Accounts?ConnectionTimeout=30&AppId=MY-APP-ID&Query=Safe=MY-SAFE;UserName={{ .remoteRef.key }};Address={{ .remoteRef.property }}"
      timeout: 30s
      result:
        jsonPath: $.Content
      caBundle: ...
```
2. Create an external secret using this secretstore
```
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook-example
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: cyberark-test
    kind: ClusterSecretStore
  target:
    name: example-sync
  data:
  - secretKey: username
    remoteRef:
      key: <cyberark username field>
      property: <cyberark address field>
      decodingStrategy: Auto
```
3. Kubernetes Version: v1.25.16+5c97f5b
4. ESO Version 0.9.14

**Expected behavior**
I expect the External Secrets Operator to fetch the secret appropriately and not error

**Additional context**
Cyberark CCP (at least in our environment) doesn't allow TLS Renegotiation.  TLS Renegotiation as I understand it will only affect long-lived connections.  Webhook connects to the URL in question authenticating each request individually, thus changing this behavior should have little to no impact on other existing webhook providers.

I operate in a highly regulated environment and have sanitized this severely.  Please take my example with a grain of salt.  This same environment prevents me from pushing a pull request for review.

I tested this locally and confirmed the following code fixed our issue and passed all the tests.
```
diff --git a/pkg/common/webhook/webhook.go b/pkg/common/webhook/webhook.go
index 7a32cc3e..78a5bd3d 100644
--- a/pkg/common/webhook/webhook.go
+++ b/pkg/common/webhook/webhook.go
@@ -203,8 +203,9 @@ func (w *Webhook) GetHTTPClient(provider *Spec) (*http.Client, error) {
        }

        tlsConf := &tls.Config{
-               RootCAs:    caCertPool,
-               MinVersion: tls.VersionTLS12,
+               RootCAs:       caCertPool,
+               MinVersion:    tls.VersionTLS12,
+               Renegotiation: tls.RenegotiateOnceAsClient,
        }
        client.Transport = &http.Transport{TLSClientConfig: tlsConf}
        return client, nil
```

### PR DESCRIPTION
**Pull request by rickymulder**
* Modify webhook provider TLS config to restrict tls renegotiation to once per client
  * Addresses #3331
* Modify webhook certs validation to include intermediates held within tls.crt
  * Addresses #3080
  * [Cert-Manager recommendation](https://cert-manager.io/docs/configuration/ca) for CA issuer

## Problem Statement

* The Webhook provider cannot handle tls cert validation when presented a chain in `tls.crt`
* The Webhook provider TLS settings do not set renegotiation
  * cyberark CCP requires renegotiation settings are provided during the handshake

## Related Issue

Fixes #3080 
Fixes #3331 

## Proposed Changes

How do you like to solve the issue and why?
* Add at least the first intermediate cert to the certPool for validation, thus allowing cert-manager CA Issuer certs to succeed validation
* Setting TLS Renegotiation on the webhook provider to once per client resolves Cyberark CCP's issue and should have little to no impact on other implementations of the webhook provider.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

File: pkg/controllers/crds/crds_controller.go [hunk 1]
```diff
@@ -438,6 +447,42 @@ func (r *Reconciler) CreateCACert(begin, end time.Time) (*KeyPairArtifacts, erro
 	return &KeyPairArtifacts{Cert: cert, Key: key, CertPEM: certPEM, KeyPEM: keyPEM}, nil
 }
 
+func (r *Reconciler) CreateCAChain(ca *KeyPairArtifacts, begin, end time.Time) (*KeyPairArtifacts, error) {
```
Comment (Skarlso) [inline pkg/controllers/crds/crds_controller.go:450]: This function is the same as the one above with the only exception that it's using `r.CAChainName` instead of `r.CAName`. Please refactor `CreateCACert` to accept two strings and then call them accordingly.

I wonder why the duplication check didn't catch that. 🤔 


Also, why you're here. There is a function calling Reconcile with a lock but it's _not_ using a pointer receiver. :O 

I wonder how that ever worked. It's `checkCRDs` and `checkEndpoints`. Could you please fix them to use a pointer receiver instead? Thanks. :)

Comment (Skarlso) [reply pkg/controllers/crds/crds_controller.go:450]: ah, you're right. I missed the parameters for `der, err := x509.CreateCertificate(rand.Reader, templ, templ, key.Public(), key)`. Well, if you can without making it way more complex than it's worth, then okay. Otherwise it's fine.

Comment (rickymulder) [reply pkg/controllers/crds/crds_controller.go:450]: pointer receiver fixed.

Comment (Skarlso) [reply pkg/controllers/crds/crds_controller.go:450]: Thanks for trying. 😊

**Comment by rickymulder** [comment]
@Skarlso 
Might I ask what timeframe I should expect this to be merged in?  Also, when a new image might be built from this?

**Comment by Skarlso** [comment]
@rickymulder Hello. Can you please update the branch so I can merge it?

Also, to answer your question, I have no idea. :)

**Review by Skarlso — APPROVED** [review]

**Comment by rickymulder** [comment]
> @rickymulder Hello. :)
> 
> Unfortunately, I don't know. :D
> 
> Cheers. :)

Fair enough.  I'll watch for the next release.  Thank you for the assist!

**Comment by Skarlso** [comment]
No worries. I didn't yet learn how to do a release. I'll try to do that next time.
