### PR TITLE
fix: Improved error message for unsupported secret store kind

### LINKED ISSUE #4397: PushSecret stopped updating after helm chart upgrade
**Describe the bug**
After updating to Helm chart version [v0.14.0](https://github.com/external-secrets/external-secrets/releases/tag/v0.14.0) my PushSecret stopped updating, and errors with: `"panic":"runtime error: invalid memory address or nil pointer dereference"`

**To Reproduce**
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: home-tls
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: home-tls
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: home-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: home-tls
          property: *key
```

**Expected behavior**
I expected my PushSecret to continue updating.

**Additional context**
I have downgraded for now back to [v0.13.0](https://github.com/external-secrets/external-secrets/releases/tag/v0.13.0), and it immediately started updating again.

### PR DESCRIPTION
**Pull request by peterswica**
## Problem Statement

We had an invalid `secretStoreRef` at runtime and got this issue when upgrading from `0.9`. 

```
{"level":"error","ts":1738597140.1073334,"logger":"controllers.ExternalSecret","msg":"unable to determine if store is managed","ExternalSecret":{...},"error":"expected pointer, but got invalid kind","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:201\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:224"}
```

The fix was to update the `Kind` value, which was hard to see from the error message. This PR fixes that.

@johnny-nguyen-gusto is a co-author and helped replicate the issue with me

## Related Issue

#4399 

## Proposed Changes

How do you like to solve the issue and why?

## Checklist

- [X] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [X] All commits are signed with `git commit --signoff`
- [X] My changes have reasonable test coverage
- [X] All tests pass with `make test`
- [X] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

File: pkg/controllers/externalsecret/externalsecret_controller.go [hunk 1]
```diff
@@ -833,6 +833,9 @@ func shouldSkipUnmanagedStore(ctx context.Context, namespace string, r *Reconcil
 			store = &esv1beta1.ClusterSecretStore{}
 			namespace = ""
 		}
+                default:
+                    return false, fmt.Errorf("Unsupported secret store kind: %s", ref.Kind)
```
Comment (Skarlso) [inline pkg/controllers/externalsecret/externalsecret_controller.go:837]:
```suggestion
                    return false, fmt.Errorf("unsupported secret store kind: %s", ref.Kind)
```

File: pkg/controllers/externalsecret/externalsecret_controller.go [hunk 2]
```diff
@@ -833,6 +833,9 @@ func shouldSkipUnmanagedStore(ctx context.Context, namespace string, r *Reconcil
 			store = &esv1beta1.ClusterSecretStore{}
 			namespace = ""
 		}
+                default:
```
Comment (Skarlso) [inline pkg/controllers/externalsecret/externalsecret_controller.go:836]: Oh, this default is outside of the switch statement...

File: pkg/controllers/externalsecret/externalsecret_controller.go (hunk 1 above)
Comment (peterswica) [reply pkg/controllers/externalsecret/externalsecret_controller.go:837]: Will update

File: pkg/controllers/externalsecret/externalsecret_controller.go (hunk 2 above)
Comment (peterswica) [reply pkg/controllers/externalsecret/externalsecret_controller.go:836]: Damn, that's a rookie mistake of mine -- sorry about that. Will fix in a revision

Comment (peterswica) [reply pkg/controllers/externalsecret/externalsecret_controller.go:835]: I could have sworn I ran `make test` before (I definitely ran `make reviewable`), but we should be good to go now. Again, sorry for wasting your time on a silly syntax mistake.

```
make test
5:27:35 [ OK ] go test unit-tests
make fmt
15:32:41 [ OK ] Ensured consistent code style
```

**Review by Skarlso — APPROVED** [review]
