### PR TITLE
fix(provider): configure TLS for secret server provider

### LINKED ISSUE #5543: Error making GET request - TLS: failed to verify certificate: x509: certificate signed by unknown authority
We are unable to make a secure connection to our on-premise Secret Server. 
The error log from the external-secrets pod is: 
```
Error making GET request: Get "<secret server url>": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

It appears some providers have a CAprovider or CAbundle option, while Secret Server does not. 

**To Reproduce**
1. provide all relevant manifests
```
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secret-server-store
spec:
  provider:
    secretserver:
      serverURL: "URL removed"
      username:
        value: "externalsecrets"
      password:
        secretRef:
          name: external-secrets-pw
          key: password
```
```
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: secret-server-external-devdba
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: SecretStore
        name: secret-server-store
    data:
      - secretKey: SecretServerValue 
        remoteRef:
          key: "key removed" 
          property: 
```

2. Versions: 
ESO: oci.external-secrets.io/external-secrets/external-secrets:v0.20.4
Kubernetes Version: v1.31.12 +rke2r1

**Expected behavior**
Secrets returned from Secret Server provider through ESO, without a TLS error.

### PR DESCRIPTION
**Pull request by Lumexralph**
## Problem Statement

As stated in this issue #5543, there's an issue when Delineas Secret Server URL certificate is being verified,  this occurs when the server URL is using HTTPS.

## Related Issue

Fixes #5543

## Proposed Changes

How do you like to solve the issue and why?

## Format

Please ensure that your PR follows the following format for the title:
```
feat(scope): add new feature
fix(scope): fix bug
docs(scope): update documentation
chore(scope): update build tool or dependencies
ref(scope): refactor code
clean(scope): provider cleanup
test(scope): add tests
perf(scope): improve performance
desig(scope): improve design
```

Where `scope` is _optionally_ one of:
- charts
- release
- testing
- security
- templating

## Checklist

- [ ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ ] All commits are signed with `git commit --signoff`
- [ ] My changes have reasonable test coverage
- [ ] All tests pass with `make test`
- [ ] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

File: apis/externalsecrets/v1/secretsstore_secretserver_types.go [hunk 1]
```diff
@@ -51,4 +50,14 @@ type SecretServerProvider struct {
 	// URL to your secret server installation
 	// +required
 	ServerURL string `json:"serverURL"`
+
+	// PEM/base64 encoded CA bundle used to validate Secret ServerURL. Only used
+	// if the ServerURL URL is using HTTPS protocol. If not set the system root certificates
+	// are used to validate the TLS connection.
+	// +optional
+	CABundle []byte `json:"caBundle,omitempty"`
```
Comment (bharath-b-rh) [inline apis/externalsecrets/v1/secretsstore_secretserver_types.go:58]: nit: Do we need both options `CABundle` and `CAProvider`. I feel `CAProvider` is a better option, than having to maintain the raw data in the `SecretStore`.
I have no idea how it's used in SecretServer, so please disregard, if it's required.

File: providers/v1/secretserver/provider.go [hunk 2]
```diff
@@ -72,14 +74,39 @@ func (p *Provider) NewClient(ctx context.Context, store esv1.GenericStore, kube
...
+		}
+
+		caCertPool := x509.NewCertPool()
+		if !caCertPool.AppendCertsFromPEM(cert) {
+			return nil, errors.New("failed to append caBundle")
+		}
+
+		ssConfig.TLSClientConfig = &tls.Config{
+			RootCAs:    caCertPool,
+			MinVersion: tls.VersionTLS12,
```
Comment (bharath-b-rh) [inline providers/v1/secretserver/provider.go:105]: Should we make this as well configurable, along with `MaxVersion`?

File: apis/externalsecrets/v1/secretsstore_secretserver_types.go (hunk 1 above)
Comment (Lumexralph) [reply apis/externalsecrets/v1/secretsstore_secretserver_types.go:58]: I don't think it's required, really. Anyone can be used to configure TLS, I was trying to be consistent with existing implementations, but if we think we don't need it, I am happy to remove it.

File: providers/v1/secretserver/provider.go (hunk 2 above)
Comment (Lumexralph) [reply providers/v1/secretserver/provider.go:105]: I don't have a strong opinion, but since the  minimum version we should support is `TLS 1.2`, we can make it the default. I think we can make it configurable with some validation using the webhook

What happens when a user supplies a deprecated version, like `< TLS 1.2`?

File: apis/externalsecrets/v1/secretsstore_secretserver_types.go (hunk 1 above)
Comment (Skarlso) [reply apis/externalsecrets/v1/secretsstore_secretserver_types.go:58]: Consistency is better here. :)

File: providers/v1/secretserver/provider.go (hunk 2 above)
Comment (Skarlso) [reply providers/v1/secretserver/provider.go:105]: Nothing else configures this, so I'm okay with hardcoding it.

If we configure it, would be nice to configure it for everything. :)

**Review by Skarlso — DISMISSED** [review]

**Comment by Skarlso** [comment]
Needs a `make check-diff` and then commit the diff. :)

**Comment by Lumexralph** [comment]
> Needs a `make check-diff` and then commit the diff. :)

yep, working on that now. Do we have it documented anywhere what to do when we update CRDs for tests?

I couldn't find any

**Comment by Skarlso** [comment]
You just run make check-diff and commit the result. :)

**Comment by Lumexralph** [comment]
> You just run make check-diff and commit the result. :)

Just made the fix, would need another approval from you 🙏🏽

**Review by Skarlso — APPROVED** [review]
